---
classes:
  - forumone::varnish
  - forumone::nodejs
  - forumone::ruby
  - redis

forumone::webserver::webserver: nginx

forumone::php::prefix: "php70u"

forumone::php::modules:
  - gd
  - opcache
  - pecl-redis
