<?php
/**
 * @file
 * Custom tokens for CBC.
 */

/**
 * Implements hook_token_info_alter().
 */
function cbc_token_token_info_alter(&$data) {
  $data['tokens']['current-page']['hero-image'] = [
    'description' => t('Hero header image taken from the page context.'),
    'name' => t('Hero header image'),
  ];
}

/**
 * Implements hook_tokens().
 */
function cbc_token_tokens($type, $tokens, array $data, array $options, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
  if ($type == 'current-page' && isset($tokens['hero-image'])) {
    // Default image
    $image = Drupal\Core\Url::fromUri('base://themes/cbcny_theme/images/bg/hero--post.jpg', ['absolute' => TRUE])->toString();

    // If we're on a node, and it has field_hero_header, and it has a value, use that path.
    if (isset($data['node']) && !empty($data['node']) && !empty($data['node']->field_hero->getValue())) {
      $image = $data['node']->field_hero->entity->field_image->entity->url();
    }

    return [
      '[current-page:hero-image]' => $image,
    ];
  }
}

