# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: 'app'

# The runtime the application uses.
type: 'php:7.1'

# Configuration of the build of this application.
build:
    flavor: composer

access:
    ssh: admin

# Include the PHP Redis extension
runtime:
    sizing_hints:
        request_memory: 11
    extensions:
        - redis

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'mysql:mysql'
    solr: 'solr:main'
    redis: "redis:redis"

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'web'

            # How long to allow static assets from this location to be cached.
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as 365 days).
            expires: '1M'

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            # Can be true, false or a URI path string.
            passthru: '/index.php'
        '/sites/default/files':
            root: 'web/sites/default/files'
            expires: '1h'
            scripts: false
            passthru: '/index.php'
            rules:
                # compressed css/js cache for a year.
                '^/sites/default/files/(css|js)/':
                  expires: '1y'

# The size of the persistent disk of the application (in MB).
disk: 6144

# The mounts that will be performed when the package is deployed.
mounts:
    '/web/sites/default/files': 'shared:files/files'
    '/tmp': 'shared:files/tmp'
    '/private': 'shared:files/private'
    '/drush-backups': 'shared:files/drush-backups'
    '/.npm': 'shared:files/.npm'
    '/web/themes/cbcny_theme/node_modules': 'shared:files/theme/node_modules'
    '/web/themes/cbcny_theme/bower_components': 'shared:files/theme/bower_components'
    '/web/themes/cbcny_theme/.sass_cache': 'shared:files/theme/.sass_cache'
    '/web/themes/cbcny_theme/sass_partials/sass-globbing': 'shared:files/theme/sass_partials/sass-globbing'
    "/.platformsh": 'shared:files/.platformsh'

# The build-time dependencies of the app.
dependencies:
  php:
    'drush/drush': '~8'
    'drupal/console': '@stable'
  nodejs:
    grunt-cli: "~1"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build: |
      set -e
      SIMPLETEST_BASE_URL=http://localhost SIMPLETEST_DB=sqlite://localhost//tmp/db.sqlite ~/vendor/bin/phpunit -c ~/web/core --verbose ~/web/modules/custom/
      cd web/themes/cbcny_theme
      npm install
      grunt build
      cd ~
      curl -sfSL -o .global/bin/platform.phar https://github.com/platformsh/platformsh-cli/releases/download/v3.21.0/platform.phar
    deploy: |
      set -e
      cd web
      drush -y updatedb --entity-updates
      drush -y config-import
      drush -y cr

# The configuration of scheduled execution.
crons:
    # Drupal core cron.
    drupal:
        spec: '*/5 * * * *'
        cmd: 'cd web ; drush core-cron'
    # Import new podcast episodes from Soundcloud.
    podcast:
        spec: '0,15,30,45 * * * *'
        cmd: 'cd web ; drush mi --group=cbc_podcast'
    # Create a backup snapshot.
    snapshot:
        spec: '30 4 * * *'
        cmd: '/bin/sh /app/scripts/snapshot.sh'
    # Force redeploy to check and re-issue SSL certs if necessary.
    cert-check:
        spec: '45 4 * * *'
        cmd: '/app/scripts/redeploy.sh'
