# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: 'drupal6'

# The runtime the application uses.
type: 'php:5.6'

# Configuration of the build of this application.
build:
    flavor: none

access:
    ssh: admin

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    database: 'drupal6_mysql:mysql'
    solr: 'drupal6_solr:solr'

# The configuration of app when it is exposed to the web.
web:
    # Specific parameters for different URL prefixes.
    locations:
        '/':
            # The folder from which to serve static assets, for this location.
            #
            # This is a filesystem path, relative to the application root.
            root: 'public'

            # How long to allow static assets from this location to be cached.
            # Can be a time in seconds, or -1 for no caching. Times can be
            # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
            # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as 365 days).
            expires: "1w"

            # Whether to forward disallowed and missing resources from this
            # location to the application.
            # Can be true, false or a URI path string.
            passthru: '/index.php'

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    '/drupal6/public/sites/default/files': 'shared:files/drupal6-files'
    '/tmp': 'shared:files/drupal6-tmp'
    '/private': 'shared:files/drupal6-private'
    '/drush-backups': 'shared:files/drush-backups'

# The build-time dependencies of the app.
dependencies:
  php:
    'drush/drush': '~7'

# The hooks executed at various points in the lifecycle of the application.
hooks:
    deploy: |
      set -e
      cd web
      drush cc --all
      drush updb -y
      drush fra -y
      drush cc --all

# The configuration of scheduled execution.
crons:
    drupal:
        spec: '*/20 * * * *'
        cmd: 'cd public ; drush core-cron'