action.configuration.node_make_searchable_action:
  type: action_configuration_default
  label: 'Make content searchable'

action.configuration.node_make_unsearchable_action:
  type: action_configuration_default
  label: 'Make content unsearchable'
