cbc_status_bar.settings:
  type: config_object
  label: 'CBC Status Bar settings'
  mapping:
    enabled:
      type: boolean
      label: Enable status bar
    message:
      type: string
      label: 'Status bar message'
