http://admin.cbcny.org/:
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: false
    headers:
    - Accept
    - Accept-Language
  redirects:
    expires: -1s
    paths: {}
  ssi:
    enabled: true
  type: upstream
  upstream: app:http
http://keycdn.cbcny.org/:
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: false
    headers:
    - Accept
    - Accept-Language
  redirects:
    expires: -1s
    paths: {}
  ssi:
    enabled: true
  type: upstream
  upstream: app:http
http://www.{default}/:
  redirects:
    expires: -1s
    paths: {}
  to: https://{default}/
  type: redirect
http://{default}/:
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: false
    headers:
    - Accept
    - Accept-Language
  redirects:
    expires: -1s
    paths: {}
  ssi:
    enabled: true
  type: upstream
  upstream: app:http
