http://old.{default}/:
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: false
    headers:
    - Accept
    - Accept-Language
  redirects:
    expires: -1s
    paths: {}
  ssi:
    enabled: true
  type: upstream
  upstream: drupal6:http
https://www.{default}/:
  to: https://{default}/
  type: redirect
https://{default}/:
  cache:
    cookies:
    - '*'
    default_ttl: 0
    enabled: false
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: true
  type: upstream
  upstream: app:http
